# Generated by Django 3.0 on 2020-12-23 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_answer_question'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='answer_title',
            new_name='title',
        ),
    ]
